<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Crowsnest.Core\Crowsnest.Core.csproj" />
    <ProjectReference Include="..\Crowsnest.SimConnect\Crowsnest.SimConnect.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
